spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/alphano
    username: sa
    password:
    driver-class-name: org.h2.Driver

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG