spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/alphano
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  cloud:
    aws:
      region:
        static: ap-northeast-2
      sns:
        topic:
          match-request: arn:aws:sns:ap-northeast-2:748178823461:alphano-match-request
          match-result: arn:aws:sns:ap-northeast-2:748178823461:alphano-match-result
      sqs:
        queues:
          backend: alphano-BackendQueue
          match-worker: alphano-MatchWorkerQueue

logging:
  level:
    org.hibernate.SQL: DEBUG