spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/alphano
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        presigned:
          expire-minutes:  15
      sns:
        topic:
          match-request: arn:aws:sns:ap-northeast-2:748178823461:alphano-match-request
          match-result: arn:aws:sns:ap-northeast-2:748178823461:alphano-match-result
      sqs:
        queues:
          backend: alphano-BackendQueue
          match-worker: alphano-MatchWorkerQueue

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  # 개발용
  secret: 4dc310ff43f20d5dcd9fd9ac7b37e9f0b3b2927bb618195a3f93d47d3cbec8b6c311e2d6f221fbbe0f2cb9534400b94881ee88d71aff746e4b2d2e6fba8ee857
  expiration:
    access: 1800000 # 30분
    refresh: 1209600000 # 14일

logging:
  level:
    org.hibernate.SQL: DEBUG